name: Create credentials.py

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (or any other branch you choose)
  pull_request:
    branches:
      - main

jobs:
  create_credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create credentials.py
        run: |
          cat << EOF > credentials.py
          # credentials.py

          # SECURITY WARNING:
          # NEVER commit this file to version control (e.g., Git).
          # Replace the following placeholder with a strong, unique secret key.
          # You can generate one using:
          #     python -c "import secrets; print(secrets.token_urlsafe(50))"
          # For production, consider storing the secret key in an environment variable.
          SECRET_KEY = ''

          # Database configuration
          # NOTE: This is a sample SQLite configuration for initial setup and testing.
          # For production or more robust development, replace it with your actual database settings (e.g., PostgreSQL).
          DATABASE = {
              'ENGINE': 'django.db.backends.sqlite3',
              'NAME': 'mydatabase',  # Replace with your database name (optional)
          }
          EOF

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add credentials.py template"
